# For OLCF Summitdev
CFLAGS=-std=c++11
CC=mpiCC $(CFLAGS)
NVCC=nvcc $(CFLAGS)
TARGET=blas
OBJS=$(TARGET).o $(TARGET)cu.o params.o

$(TARGET): $(OBJS)
	$(CC) -o $@ $(OBJS) -lcublas -lcudart -L /sw/summitdev/cuda/9.0.69/lib64

$(TARGET).o: $(TARGET).cpp common.h params.h comp.h
	$(CC) -c $<

$(TARGET)cu.o: $(TARGET).cu common.h params.h comp.h
	$(NVCC) -o $@ -c $<

params.o: params.cpp params.h
	$(CC) -c $<

test:
	jsrun -n 4 ./$(TARGET)

clean:
	rm -f $(TARGET) $(OBJS)
